import { SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-6xl flex-col items-center justify-center px-4">
        <header className=" flex w-full items-center justify-between border-b-2 border-my_grey pb-3 pl-2">
          <h1 className="ml-4 inline-block text-3xl">Quiz</h1>
          <div className="flex items-center gap-7">
            <Link href={""} className=" text-black opacity-50">
              {" "}
              Purchase Subscription
            </Link>
            <select
              name="lang"
              id="lang"
              className="rounded-sm bg-my_grey p-1 px-4 text-white"
            >
              <option value="english">English</option>
            </select>
            <SignedIn>
              {/* Mount the UserButton component */}
              <UserButton />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton>
                <span className=" cursor-pointer rounded-sm bg-my_green p-1 px-4 text-white">
                  Login
                </span>
              </SignInButton>
            </SignedOut>
          </div>
        </header>
        <h1 className="ml-6 mt-10 self-start text-5xl font-bold text-[#146C94DE]">
          {" "}
          Unlock the Road
        </h1>
        <h2 className="ml-10 self-start text-3xl font-semibold text-[#146C94DE]">
          Achieve success with us
        </h2>

        <span className=" ml-6 mt-10 self-start border-l-[1px] border-[#1a120b85] pl-2">
          Master theory test and become a skilled driver with ease.
        </span>
        <span className=" ml-6 mt-4 self-start border-l-[1px] border-[#1a120b85] pl-2">
          Join thousands of satisfied learners and pass your theory test
          confidently.
        </span>
        <span className=" ml-6 mt-4 self-start border-l-[1px] border-[#1a120b85] pl-2">
          Empower yourself with knowledge and conquer the driving theory test.
        </span>

        <article className=" mb-50 relative ml-16 mt-16 flex flex-col gap-2 self-start rounded-md bg-[#146C94] px-4 py-2 text-white shadow-md shadow-[#146C94]">
          {" "}
          <span className=" self-end font-medium">Unlimited access</span>
          <strong className="px-10 text-2xl">99 KR ONLY PER MOUNTH</strong>
          <span className=" self-start font-medium">
            No bindings, cancel anytime*
          </span>
          <span className=" absolute bottom-[-2rem] left-1/2  rounded-b-md bg-[#1B9C85] px-2 py-1 shadow-md shadow-[#1B9C85]">
            Purchase Subscription
          </span>
        </article>
        <footer className="shadow-slate-300 mt-16 rounded-md bg-[#9BA4B5] p-3 text-sm text-white shadow-xl">
          © 2023 DriveSmart. All rights reserved. |{" "}
          <Link href={""}>Privacy Policy</Link> |{" "}
          <Link href={""}>Terms of Service</Link>|{" "}
          <Link href={""}>Contact Us</Link>
        </footer>
      </main>
    </>
  );
};

export default Home;
